/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String logo_dark = "assets/logo_dark.svg";
  static const String logo_with_name = "assets/logo_with_name.svg";
  static const String not_found = "assets/not_found.json";
}
