/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String animated_coins = "assets/animated_coins.json";
  static const String animation_caution = "assets/animation_caution.json";
  static const String animation_spray_new = "assets/animation_spray_new.json";
  static const String bet_smarter = "assets/bet_smarter.svg";
  static const String calc_risk = "assets/calc_risk.svg";
  static const String coins = "assets/coins.svg";
  static const String coins_animation = "assets/coins_animation.json";
  static const String empty = "assets/empty.json";
  static const String flutterwave = "assets/flutterwave.png";
  static const String hurry_animation = "assets/hurry_animation.json";
  static const String intro_background = "assets/intro_background.svg";
  static const String intro_st1 = "assets/intro_st1.svg";
  static const String intro_st2 = "assets/intro_st2.svg";
  static const String intro_st3 = "assets/intro_st3.svg";
  static const String keys = "assets/keys.json";
  static const String licence_lock = "assets/licence_lock.json";
  static const String linear_loader = "assets/linear_loader.json";
  static const String loading_linear = "assets/loading_linear.json";
  static const String logo = "assets/logo.svg";
  static const String logo_dark = "assets/logo_dark.svg";
  static const String logo_with_name = "assets/logo_with_name.svg";
  static const String master_card = "assets/master_card.png";
  static const String not_found = "assets/not_found.json";
  static const String pay_failed = "assets/pay_failed.json";
  static const String pay_success = "assets/pay_success.json";
  static const String paystack = "assets/paystack.svg";
  static const String spray_coins = "assets/spray_coins.json";
  static const String trohpy = "assets/trohpy.json";
  static const String trophy_icon = "assets/trophy_icon.svg";
  static const String trophy_thick = "assets/trophy_thick.svg";
  static const String verve_card = "assets/verve_card.png";
  static const String visa_card = "assets/visa_card.png";
  static const String wallet = "assets/wallet.json";
  static const String wallet_fund = "assets/wallet_fund.svg";
}
